# Generated by Django 5.1.3 on 2024-11-11 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField()),
                ('instrutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
